export const metadata = {
  title: "March Madness ML - Portfolio",
  description:
    "End-to-end March Madness machine learning pipeline, feature engineering, model benchmarking, and XGBoost optimization.",
};

export default function MarchMadnessMLPage() {
  const pipelineSteps = [
    {
      step: "STEP 01",
      title: "Game-Level Dataset Construction",
      text: "Every pair of rows in the raw tournament CSV represented one game. The first task was restructuring this into a proper one-row-per-game format with Team A vs Team B and the binary target ATeamWin. Data was sorted by year in descending order so recent tournaments appeared first, and pairings were generated by year using cumulative indexing.",
      stat: "1,070 games structured",
    },
    {
      step: "STEP 02",
      title: "Merging 21 Data Sources",
      text: "21 external team-level datasets were merged using a safe YEAR + TEAM NO key to avoid leakage. Sources ranged from 538 Power Ratings and KenPom/Barttorvik to AP Poll, EvanMiya ratings, and heat-check tournament indices. Each source was profiled so sparse and leakage-prone columns were excluded.",
      stat: "760 total columns after merge",
    },
    {
      step: "STEP 03",
      title: "A-minus-B Differential Features",
      text: "Rather than raw team stats, each numeric feature was converted to an A-minus-B differential to capture relative matchup strength. Seed diff, seed sum, and seed product were added as baseline matchup signals.",
      stat: "745 differential features engineered",
    },
    {
      step: "STEP 04",
      title: "Upset Uncertainty Index",
      text: "A custom feature measured how much major rating systems disagree about a matchup. By z-scoring seven key differential signals and measuring spread plus sign disagreement, an UpsetUncertainty feature was created to reduce upset miscalls.",
      stat: "+0.93pp accuracy gain",
    },
    {
      step: "STEP 05",
      title: "Model Benchmarking",
      text: "Seven model families were trained on an 80/20 stratified split: Logistic Regression, Neural Network (MLP), SVM, Random Forest, Extra Trees, HistGradientBoosting, and Naive Bayes. Evaluation used both accuracy and log loss.",
      stat: "7 models benchmarked head-to-head",
    },
    {
      step: "STEP 06",
      title: "XGBoost + Hyperparameter Tuning",
      text: "XGBoost outperformed the initial set at 88.3% accuracy. A 14-trial random search with 3-fold stratified CV found stronger settings, and the tuned + retrained model with UpsetUncertainty features achieved the best final log loss.",
      stat: "0.236 final log loss",
    },
  ];

  const leaderboard = [
    { model: "XGBoost (Tuned + UpsetUncertainty)", accuracy: "89.25%", logLoss: "0.238", width: "89.25%", badge: "BEST", best: true },
    { model: "XGBoost (Tuned CV)", accuracy: "88.32%", logLoss: "0.236", width: "88%", badge: "2ND", best: true, second: true },
    { model: "XGBoost (Baseline)", accuracy: "88.32%", logLoss: "0.295", width: "88%" },
    { model: "HistGradientBoosting", accuracy: "85.98%", logLoss: "0.515", width: "85%" },
    { model: "Logistic Regression", accuracy: "83.64%", logLoss: "0.484", width: "83%" },
    { model: "Random Forest", accuracy: "76.64%", logLoss: "0.466", width: "76%" },
    { model: "SVM (RBF)", accuracy: "73.36%", logLoss: "0.513", width: "73%" },
    { model: "Neural Network (MLP)", accuracy: "71.96%", logLoss: "1.209", width: "71%" },
    { model: "Naive Bayes", accuracy: "64.02%", logLoss: "11.47", width: "64%" },
  ];

  const skills = [
    ["🔧", "Data Engineering", "Structured a messy multi-year bracket CSV into a clean one-row-per-game format using pandas grouping and indexing logic."],
    ["🗂️", "Multi-Source Feature Fusion", "Safely joined 21 external datasets on YEAR + TEAM NO and excluded leakage-prone and sparse columns programmatically."],
    ["🧠", "Feature Engineering Craft", "Converted raw stats into A-vs-B differentials and added a custom UpsetUncertainty index based on rating disagreement."],
    ["📊", "Model Selection & Benchmarking", "Trained and evaluated 8 model families with consistent preprocessing and compared both accuracy and log loss."],
    ["⚡", "Hyperparameter Optimization", "Implemented 14-trial random search with 3-fold stratified CV to optimize XGBoost parameters."],
    ["🎨", "Visualization & Communication", "Built custom Matplotlib + Plotly visuals and exported interactive outputs for web portfolio presentation."],
  ];

  return (
    <>
      <div className="mm-root">
        <section className="hero">
          <div className="hero-glow" />
          <div className="hero-glow2" />
          <div className="tag">{"// Machine Learning · Sports Analytics · Feature Engineering"}</div>
          <h1>
            Predicting <span>March Madness</span> with XGBoost
          </h1>
          <p className="hero-sub">
            An end-to-end machine learning pipeline that ingests from 21 data sources, achieving 88.3% accuracy predicting NCAA tournament outcomes.
          </p>
          <div className="hero-meta">
            <span className="meta-pill">Python · Pandas · Scikit-Learn</span>
            <span className="meta-pill">1,070 Games · 2008–2025</span>
            <span className="meta-pill">89.25% Accuracy</span>
            <span className="meta-pill">0.238 Log Loss</span>
          </div>
          <div className="hero-divider" />
        </section>

        <section className="section">
          <div className="section-label">{"// 01 — The Problem"}</div>
          <h2 className="section-title">
          Can statistical models outperform
            <br />
            <em>seed-based intuition?</em>
          </h2>
          <p className="body-text">
          The idea: pull together every meaningful team performance metric available, engineer them into matchup-level features, and see if a model can predict game outcomes better than a typical bracket picker.
          </p>
          <div className="stat-row">
            <div className="big-stat"><div className="num">21</div><div className="label">Data Sources Merged</div></div>
            <div className="stat-divider" />
            <div className="big-stat"><div className="num">600<span>+</span></div><div className="label">Variables</div></div>
            <div className="stat-divider" />
            <div className="big-stat"><div className="num">89.2<span>%</span></div><div className="label">Final Accuracy</div></div>
            <div className="stat-divider" />
            <div className="big-stat"><div className="num">23</div><div className="label">Misclassified (of 214)</div></div>
          </div>
        </section>

        <section className="section" style={{ paddingTop: 0 }}>
          <div className="section-label">{"// 02 — The Pipeline"}</div>
          <h2 className="section-title">
          Six steps from raw data to
          <br />
          <em>predictive model</em>
          </h2>
          <div className="story-grid">
            {pipelineSteps.map((item) => (
              <div key={item.step} className="story-card">
                <div className="step-num">{item.step}</div>
                <h3>{item.title}</h3>
                <p>{item.text}</p>
                <div className="card-stat">{item.stat}</div>
              </div>
            ))}
          </div>
        </section>

        <section className="section results-section">
          <div className="section-label">{"// 03 — Results"}</div>
          <h2 className="section-title">
            The <em>leaderboard</em>
          </h2>
          <p className="body-text">
          All models ranked by accuracy. Log loss was included as a secondary metric. It penalizes overconfident wrong predictions and gives a fuller picture of model quality than accuracy alone.
          </p>
          <div className="leaderboard">
            <table>
              <thead>
                <tr>
                  <th>Model</th>
                  <th>Accuracy</th>
                  <th>Log Loss</th>
                  <th>Accuracy Bar</th>
                </tr>
              </thead>
              <tbody>
                {leaderboard.map((row) => (
                  <tr key={row.model} className={row.best ? "best-row" : ""}>
                    <td>
                      {row.model}
                      {row.badge && (
                        <span className={`best-badge ${row.second ? "second-badge" : ""}`}>{row.badge}</span>
                      )}
                    </td>
                    <td>{row.accuracy}</td>
                    <td>{row.logLoss}</td>
                    <td>
                      <div className="bar-wrapper">
                        <div className="bar-track">
                          <div
                            className={`bar-fill ${row.second ? "bar-second" : ""}`}
                            style={{ width: row.width }}
                          />
                        </div>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section className="section">
          <div className="section-label">{"// 04 — Analysis"}</div>
          <h2 className="section-title">
            Model <em>analysis</em>
          </h2>
          <p className="body-text">
            Two focused diagnostics summarize the final model: confusion behavior
            and feature-level contribution.
          </p>

          <div className="analysis-grid">
            <div className="analysis-card">
              <div className="analysis-head">
                <h3>Confusion matrix</h3>
                <p>Shows where the retrained XGBoost gets predictions right and wrong.</p>
              </div>
              <div className="analysis-frame">
                <iframe
                  title="Confusion matrix"
                  src="/march-madness-charts/02_confusion_matrix.html"
                  className="analysis-iframe"
                  loading="lazy"
                  sandbox="allow-scripts allow-same-origin"
                />
              </div>
            </div>

            <div className="analysis-card">
              <div className="analysis-head">
                <h3>Top feature importances</h3>
                <p>Highlights the signals that most influenced XGBoost decisions.</p>
              </div>
              <div className="analysis-frame">
                <iframe
                  title="Top feature importances"
                  src="/march-madness-charts/03_top_feature_importances.html"
                  className="analysis-iframe"
                  loading="lazy"
                  sandbox="allow-scripts allow-same-origin"
                />
              </div>
            </div>
          </div>
        </section>

        <section className="section panel-section">
          <div className="section-label">{"// 05 — Skills Demonstrated"}</div>
          <h2 className="section-title">
            What this project <em>proves</em>
          </h2>
          <div className="skills-grid">
            {skills.map(([icon, title, text]) => (
              <div key={title} className="skill-card">
                <div className="skill-title-row">
                  <div className="skill-icon">{icon}</div>
                  <h4>{title}</h4>
                </div>
                <p>{text}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="section">
          <div className="section-label">{"// 06 — See It For Yourself"}</div>
          <h2 className="section-title">
            Explore the code and
            <br />
            <em>run the project yourself</em>
          </h2>
          <div className="cta-stack">
            <p className="body-text">
              Want to see the full pipeline in action? The repository includes the
              notebook workflow, data sources, model training logic, and chart
              outputs used in this project showcase.
            </p>
            <br />
            <div className="cta-card">
              <a
                href="https://github.com/nicholasthomas18/March-Madness"
                target="_blank"
                rel="noopener noreferrer"
                className="cta-link"
              >
                github.com/nicholasthomas18/March-Madness →
              </a>
            </div>
          </div>
        </section>

        <footer>
          <p>MARCH MADNESS ML PROJECT · END-TO-END PIPELINE</p>
          <div className="footer-stack">
            {["Python", "Pandas", "NumPy", "Scikit-Learn", "XGBoost", "Matplotlib", "Plotly"].map((item) => (
              <span key={item} className="stack-pill">
                {item}
              </span>
            ))}
          </div>
        </footer>
      </div>

      <style>{`
        .mm-root { --bg:#05070D; --panel:#0A0F1F; --royal:#4169E1; --royal-light:#7DA2FF; --royal-soft:#9FB8FF; --grid:#1B2A52; --txt:#EAF0FF; --muted:#9BB0E0; --green:#3DFFC0; background:var(--bg); color:var(--txt); font-family:'Figtree',sans-serif; font-weight:300; line-height:1.7; overflow-x:hidden; }
        .mm-root *,.mm-root *::before,.mm-root *::after{ box-sizing:border-box; }
        .mm-root::before{ content:''; position:fixed; inset:0; background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.04'/%3E%3C/svg%3E"); opacity:.35; pointer-events:none; z-index:0; }
        .hero{ position:relative; min-height:70vh; display:flex; flex-direction:column; justify-content:flex-end; padding:0 8vw 6vh; overflow:hidden; }
        .hero-glow{ position:absolute; width:700px; height:700px; background:radial-gradient(circle, rgba(65,105,225,.18) 0%, transparent 70%); top:-100px; right:-200px; animation:pulse 8s ease-in-out infinite; }
        .hero-glow2{ position:absolute; width:400px; height:400px; background:radial-gradient(circle, rgba(61,255,192,.07) 0%, transparent 70%); bottom:10%; left:5%; animation:pulse 12s ease-in-out infinite reverse; }
        @keyframes pulse{ 0%,100%{ transform:scale(1) translateY(0); opacity:.8; } 50%{ transform:scale(1.12) translateY(-20px); opacity:1; } }
        .tag{ font-family:'IBM Plex Mono',monospace; font-size:.72rem; color:var(--green); letter-spacing:.15em; text-transform:uppercase; margin-bottom:1.6rem; opacity:0; animation:fadeUp .8s .2s forwards; }
        .hero h1{ font-family:'DM Serif Display',serif; font-size:clamp(3.2rem,8vw,7.5rem); line-height:1; font-style:italic; max-width:14ch; opacity:0; animation:fadeUp .9s .35s forwards; }
        .hero h1 span{ color:var(--royal-light); font-style:normal; }
        .hero-sub{ margin-top:2rem; font-size:1.1rem; color:var(--muted); max-width:52ch; font-weight:400; opacity:0; animation:fadeUp .9s .55s forwards; }
        .hero-meta{ margin-top:3rem; display:flex; gap:2.5rem; flex-wrap:wrap; opacity:0; animation:fadeUp .9s .75s forwards; }
        .meta-pill{ background:var(--panel); border:1px solid var(--grid); border-radius:4px; padding:.45rem 1rem; font-family:'IBM Plex Mono',monospace; font-size:.78rem; color:var(--royal-soft); }
        .hero-divider{ margin-top:3rem; height:1px; background:linear-gradient(90deg,transparent,var(--royal),transparent); opacity:0; animation:fadeIn 1s 1s forwards; }
        @keyframes fadeUp{ from{ opacity:0; transform:translateY(28px); } to{ opacity:1; transform:translateY(0); } }
        @keyframes fadeIn{ from{ opacity:0; } to{ opacity:1; } }
        .section{ position:relative; padding:4rem 8vw; z-index:1; }
        .section-label{ font-family:'IBM Plex Mono',monospace; font-size:.7rem; color:var(--royal); letter-spacing:.18em; text-transform:uppercase; margin-bottom:1rem; }
        .section-title{ font-family:'DM Serif Display',serif; font-size:clamp(2rem,4vw,3.2rem); line-height:1.15; margin-bottom:2.5rem; }
        .section-title em{ font-style:italic; color:var(--royal-light); }
        .body-text{ font-size:1.05rem; color:var(--muted); max-width:64ch; line-height:1.85; }
        .insight-block{ border-left:3px solid var(--royal); padding:1.5rem 2rem; background:rgba(65,105,225,.05); border-radius:0 4px 4px 0; margin:3rem 0; }
        .insight-block p{ font-family:'DM Serif Display',serif; font-size:1.3rem; font-style:italic; line-height:1.55; }
        .insight-block span{ display:block; margin-top:.75rem; font-family:'IBM Plex Mono',monospace; font-size:.72rem; color:var(--royal-soft); letter-spacing:.1em; font-style:normal; }
        .cta-stack{ margin-top:2rem; }
        .cta-card{ display:inline-block; width:fit-content; max-width:100%; border:1px solid var(--grid); background:var(--panel); border-radius:8px; padding:.9rem 1rem; }
        .cta-link{ display:inline-block; white-space:nowrap; font-family:'IBM Plex Mono',monospace; font-size:.95rem; color:var(--royal-light); text-decoration:none; border:1px solid var(--grid); background:rgba(65,105,225,.1); padding:.8rem 1.2rem; border-radius:6px; transition:all .2s ease; }
        .cta-link:hover{ color:var(--txt); border-color:var(--royal); transform:translateY(-1px); }
        .stat-row{ display:flex; gap:4rem; flex-wrap:wrap; margin-top:3.5rem; }
        .big-stat{ flex:1; min-width:140px; }
        .big-stat .num{ font-family:'DM Serif Display',serif; font-size:clamp(2.8rem,5vw,4.5rem); line-height:1; }
        .big-stat .num span{ color:var(--royal-light); }
        .big-stat .label{ font-family:'IBM Plex Mono',monospace; font-size:.72rem; color:var(--muted); letter-spacing:.12em; text-transform:uppercase; margin-top:.5rem; }
        .stat-divider{ width:1px; background:var(--grid); align-self:stretch; }
        .story-grid{ display:grid; grid-template-columns:1fr 1fr; margin-top:4rem; border:1px solid var(--grid); }
        @media (max-width:760px){ .story-grid{ grid-template-columns:1fr; } .story-card:nth-child(even){ border-right:1px solid var(--grid); } }
        .story-card{ padding:2.5rem; border-right:1px solid var(--grid); border-bottom:1px solid var(--grid); transition:background .3s; }
        .story-card:hover{ background:rgba(65,105,225,.04); }
        .story-card:nth-child(even){ border-right:none; }
        .step-num{ font-family:'IBM Plex Mono',monospace; font-size:.68rem; color:var(--royal); letter-spacing:.2em; margin-bottom:1rem; }
        .story-card h3{ font-family:'DM Serif Display',serif; font-size:1.35rem; margin-bottom:.75rem; line-height:1.2; }
        .story-card p{ font-size:.92rem; color:var(--muted); line-height:1.75; }
        .story-card .card-stat{ margin-top:1.2rem; font-family:'IBM Plex Mono',monospace; font-size:.78rem; color:var(--green); background:rgba(61,255,192,.06); border:1px solid rgba(61,255,192,.15); display:inline-block; padding:.3rem .75rem; border-radius:3px; }
        .results-section, .panel-section{ background:var(--panel); }
        .leaderboard{ margin-top:3rem; width:100%; overflow-x:auto; }
        table{ width:100%; border-collapse:collapse; font-size:.92rem; }
        thead tr{ border-bottom:2px solid var(--royal); }
        thead th{ font-family:'IBM Plex Mono',monospace; font-size:.7rem; letter-spacing:.12em; color:var(--royal-soft); text-transform:uppercase; padding:.8rem 1.2rem; text-align:left; font-weight:400; }
        tbody tr{ border-bottom:1px solid var(--grid); transition:background .2s; }
        tbody tr:hover{ background:rgba(65,105,225,.05); }
        tbody td{ padding:.9rem 1.2rem; color:var(--muted); font-family:'IBM Plex Mono',monospace; font-size:.88rem; }
        tbody td:first-child{ color:var(--txt); font-family:'Figtree',sans-serif; font-size:.95rem; font-weight:500; }
        .best-row td{ color:var(--txt)!important; }
        .best-row td:first-child{ color:var(--green)!important; font-weight:600; }
        .best-badge{ display:inline-block; background:rgba(61,255,192,.1); border:1px solid rgba(61,255,192,.3); color:var(--green); font-family:'IBM Plex Mono',monospace; font-size:.6rem; letter-spacing:.1em; padding:.15rem .5rem; border-radius:2px; margin-left:.5rem; vertical-align:middle; }
        .second-badge{ background:rgba(65,105,225,.1); border-color:rgba(65,105,225,.3); color:var(--royal-light); }
        .bar-wrapper{ display:flex; align-items:center; gap:.75rem; }
        .bar-track{ flex:1; height:4px; background:var(--grid); border-radius:2px; max-width:100px; }
        .bar-fill{ height:100%; background:var(--royal); border-radius:2px; transition:width 1s ease; }
        .bar-second{ background:var(--royal-light); }
        .best-row .bar-fill{ background:var(--green); }
        .best-row .bar-second{ background:var(--royal-light); }
        .analysis-grid{ margin-top:2.5rem; display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:1rem; align-items:start; }
        .analysis-card{ border:1px solid var(--grid); background:var(--panel); border-radius:8px; overflow:hidden; }
        .analysis-head{ padding:1rem 1.25rem; border-bottom:1px solid var(--grid); }
        .analysis-head h3{ font-family:'DM Serif Display',serif; font-size:1.2rem; margin:0; }
        .analysis-head p{ margin-top:.35rem; color:var(--muted); font-size:.9rem; }
        .analysis-frame{ position:relative; height:260px; }
        .analysis-iframe{ position:absolute; inset:0; width:100%; height:100%; border:0; background:#05070D; }
        @media (max-width:760px){ .analysis-grid{ grid-template-columns:1fr; } .analysis-frame{ height:300px; } }
        .skills-grid{ display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:1.5rem; margin-top:3rem; }
        @media (max-width:1000px){ .skills-grid{ grid-template-columns:repeat(2,minmax(0,1fr)); } }
        @media (max-width:700px){ .skills-grid{ grid-template-columns:1fr; } }
        .skill-card{ background:var(--panel); border:1px solid var(--grid); border-radius:6px; padding:2rem; transition:border-color .3s,transform .3s; }
        .skill-card:hover{ border-color:var(--royal); transform:translateY(-4px); }
        .skill-title-row{ display:flex; align-items:center; gap:.55rem; margin-bottom:.75rem; }
        .skill-icon{ font-size:1.35rem; line-height:1; }
        .skill-card h4{ font-family:'DM Serif Display',serif; font-size:1.1rem; margin:0; }
        .skill-card p{ font-size:.85rem; color:var(--muted); line-height:1.65; }
        footer{ padding:2.5rem 8vw; border-top:1px solid var(--grid); display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:1rem; }
        footer p{ font-family:'IBM Plex Mono',monospace; font-size:.72rem; color:var(--muted); letter-spacing:.1em; }
        .footer-stack{ display:flex; gap:.6rem; flex-wrap:wrap; }
        .stack-pill{ background:rgba(65,105,225,.1); border:1px solid var(--grid); color:var(--royal-soft); font-family:'IBM Plex Mono',monospace; font-size:.68rem; padding:.25rem .65rem; border-radius:2px; }
      `}</style>
    </>
  );
}

